version: '3.9'

networks:
  traefik-public:
    external: true
  internal:
    driver: overlay

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    networks:
      - internal
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      replicas: 1

  frontend:
    image: hoanglut97/lut-frontend:latest
    networks:
      - traefik-public
      - internal
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.frontend.rule=Host(`lut.longle77.site`)
        - traefik.http.services.frontend.loadbalancer.server.port=80
        - traefik.docker.network=traefik-public

  backend:
    image: hoanglut97/lut-backend:latest
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://app:app@db:5432/app?schema=public
    command: ['sh', '-lc', 'npx prisma migrate deploy && npm start']
    networks:
      - internal
    deploy:
      replicas: 1

volumes:
  db_data:
