name: cd-frontend

on:
  push:
    branches:
      - main
      - production
    paths:
      - 'services/frontend/**'
      - '.github/workflows/cd-frontend.yml'
  workflow_run:
    workflows: ["checks"]
    types:
      - completed

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lut-frontend:latest ./services/frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lut-frontend:latest
