name: Deploy to Swarm

on:
  push:
    branches: [main]
  workflow_run:
    workflows: ['cd-backend', 'cd-frontend']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/sudo_user/swarm/stacks
            docker stack deploy -c app.yml app
