name: Deploy to Swarm

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['checks']
    types:
      - completed

jobs:
  build-frontend:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lut-frontend:latest ./services/frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lut-frontend:latest

  build-backend:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lut-backend:latest ./services/backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lut-backend:latest

  deploy:
    needs:
      - build-frontend
      - build-backend
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/sudo_user/swarm/stacks
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/lut-frontend:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/lut-backend:latest
            docker stack deploy -c app.yml app